version: 2
jobs:
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
          destination: reports

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Publish to Bintray
          command: ./gradlew build bintrayUpload -PdryRun=false

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - hold:
          type: approval
          requires:
            - prepare
          filters:
            branches:
              only:
                - master
                - /release\/.*/ # all branches starting with release/
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
                - /release\/.*/ # all branches starting with release/